[package]
name = "pras"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "lexer_bench"
harness = false

[[bench]]
name = "parser_bench"
harness = false

[[bench]]
name = "compiler_bench"
harness = false
